[screenshot]

# Prompt string to use.
prompt = ":3 "

# Directory in which to save screenshots.
save_dir = "~/Pictures/Screenshots/"

# File name format.
# See: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
file_name = "screenshot_%Y-%m-%dT%H:%M:%S.png"

# Image format.
type = "png" # "jpeg", "ppm"

# JPEG quality value.
jpeg_quality = 80

# PNG compression level value.
png_level = 6

# Show or hide cursor.
cursor = false

# [rofi]
# use_rofi = true 
# rofi_theme = "maintheme"

[ask]
command = "rofi" 
args = ["-theme", "maintheme"]
